### ISSUE TITLE
PhobosDBCheckpoint::EventsAPI

### ISSUE THREAD

**Issue by klippx** [klarna/phobos_checkpoint_ui#1]
There does not seem to be an EventsAPI checked in or did I miss something?

**Comment by tulios** [comment]
It requires, at least, version __0.3.0__  of `phobos_db_checkpoint`

https://github.com/klarna/phobos_db_checkpoint/blob/master/lib/phobos_db_checkpoint/events_api.rb

gemspec is wrong, it should require `phobos_db_checkpoint`

**Comment by klippx** [comment]
Closed, fixed in v0.3.0
